# Generated by Django 2.2 on 2019-04-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encrypt_fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=300, null=True, unique=True),
        ),
    ]
